sudo: false
language: cpp
compiler:
  - gcc
  - clang
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
addons:
  apt:
    packages:
    - lcov
before_install:
  - gem install coveralls-lcov
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS_RELEASE='-ffast-math' -DCMAKE_CFLAGS_RELEASE='-ffast-math' ..
  - make VERBOSE=1 -j2
  - ctest --output-on-failure
  - ./test/vertex_dedup_test --num_iter 2 --num_vertices 100000 --epsilon 1.0e-3
  - ./test/vertex_dedup_test --num_iter 2 --num_vertices 100000 --epsilon 1.0e-4
  - ./test/transformation_test --num_iter 2 --num_vertices 100000
after_success:
  - lcov -d test -d src -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'gtest*' -o coverage.info
  - lcov --remove coverage.info 'test/*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
